## BetterShop Configuration file ##
###################################
# Colors are specified by using "&<colorcode>"
#   Color table:
#       &0 is black
#       &1 is dark blue
#       &2 is dark green
#       &3 is dark sky blue
#       &4 is red
#       &5 is magenta
#       &6 is gold or amber
#       &7 is light grey
#       &8 is dark grey
#       &9 is medium blue
#       &a is light green
#       &b is cyan
#       &c is orange-red
#       &d is pink
#       &e is yellow
#       &f is white
#
#   

##########################################
# strings section: Text used in messages #
##########################################
strings:

#
# general messages
####

    prefix: "&c[&7SHOP&c] "
    # prefix is what comes before each BetterShop message.

    permdeny: "OI! You don't have permission to do that!"
    # permdeny is the permission denied message.

    unkitem: "What the frack is &f<item>&c?"
    # unkitem is the unknown item message.

#
# shoplist messages
####

    listhead: "----- Price-List Page: <page> of <pages> -----"
    # listhead is the top of a /shoplist page.

    listtail: "----------------------------"
    # listtail is the end of a /shoplist page.

#
# shopbuy messages
####

    notforsale: "&f<item>&c is not for sale."
    # notforsale is the item not for sale message.
    buymsg: "<amt> <item> at <priceper> ... <total> total!"
    # buymsg is the message shown when successfully buying
    
